Repository facebook/buck, pull requests merged in 2020-10, with the labels that each got.

#2540 Added a rust tutorial
  docs/learning/tutorial.soy
  docs/static/buck.css
Labels: CLA Signed

#2547 Add support for async worker processes
  src/com/facebook/buck/features/js/JsUtil.java
  src/com/facebook/buck/rules/macros/WorkerMacroArg.java
  src/com/facebook/buck/shell/DefaultWorkerToolRule.java
  src/com/facebook/buck/shell/GenruleBuildable.java
  src/com/facebook/buck/shell/WorkerShellStep.java
  src/com/facebook/buck/shell/WorkerTool.java
  src/com/facebook/buck/shell/WorkerToolDescription.java
  src/com/facebook/buck/worker/BUCK
  src/com/facebook/buck/worker/WorkerProcess.java
  src/com/facebook/buck/worker/WorkerProcessParams.java
  src/com/facebook/buck/worker/WorkerProcessPool.java
  src/com/facebook/buck/worker/WorkerProcessPoolAsync.java
  src/com/facebook/buck/worker/WorkerProcessPoolFactory.java
  src/com/facebook/buck/worker/WorkerProcessPoolSync.java
  src/com/facebook/buck/worker/WorkerProcessProtocol.java
  src/com/facebook/buck/worker/WorkerProcessProtocolZero.java
  test/com/facebook/buck/shell/FakeWorkerBuilder.java
  test/com/facebook/buck/shell/WorkerShellStepTest.java
  test/com/facebook/buck/shell/WorkerToolRuleIntegrationTest.java
  test/com/facebook/buck/shell/testdata/worker_tool_test/BUCK.fixture
  test/com/facebook/buck/shell/testdata/worker_tool_test/external_tool.sh
  test/com/facebook/buck/worker/FakeWorkerProcess.java
  test/com/facebook/buck/worker/FakeWorkerProcessProtocol.java
  test/com/facebook/buck/worker/WorkerProcessPoolSyncTest.java
  test/com/facebook/buck/worker/WorkerProcessProtocolZeroTest.java
  test/com/facebook/buck/worker/WorkerProcessTest.java
Labels: CLA Signed

#2552 [Apple] Add support to AppClips
  src/com/facebook/buck/apple/AppleBinaryDescription.java
  src/com/facebook/buck/apple/AppleBundle.java
  src/com/facebook/buck/apple/AppleBundleDescription.java
  src/com/facebook/buck/apple/AppleBundleDestination.java
  src/com/facebook/buck/apple/AppleBundleDestinations.java
  src/com/facebook/buck/apple/AppleDescriptions.java
  src/com/facebook/buck/apple/AppleLibraryDescription.java
  src/com/facebook/buck/apple/AppleTestDescription.java
  src/com/facebook/buck/apple/HasAppleBundleFields.java
  src/com/facebook/buck/apple/xcode/xcodeproj/PBXCopyFilesBuildPhase.java
  src/com/facebook/buck/apple/xcode/xcodeproj/ProductTypes.java
  src/com/facebook/buck/features/apple/project/NewNativeTargetProjectMutator.java
  src/com/facebook/buck/features/apple/project/ProjectGenerator.java
  test/com/facebook/buck/apple/AppleBundleIntegrationTest.java
  test/com/facebook/buck/apple/testdata/app_bundle_with_appclip/AppClipApp/AppDelegate.swift
  test/com/facebook/buck/apple/testdata/app_bundle_with_appclip/AppClipApp/Info.plist
  test/com/facebook/buck/apple/testdata/app_bundle_with_appclip/AppClipApp/ViewController.swift
  test/com/facebook/buck/apple/testdata/app_bundle_with_appclip/AppClipApp/main.swift
  test/com/facebook/buck/apple/testdata/app_bundle_with_appclip/BUCK.fixture
  test/com/facebook/buck/apple/testdata/app_bundle_with_appclip/Clip/AppDelegate.swift
  test/com/facebook/buck/apple/testdata/app_bundle_with_appclip/Clip/BUCK.fixture
  test/com/facebook/buck/apple/testdata/app_bundle_with_appclip/Clip/Clip.entitlements
  test/com/facebook/buck/apple/testdata/app_bundle_with_appclip/Clip/Info.plist
  test/com/facebook/buck/apple/testdata/app_bundle_with_appclip/Clip/main.swift
Labels: CLA Signed, GH Review: accepted

#2555 Re-sync with internal repository
  test/com/facebook/buck/doctor/testdata/report/buck-out/log/2016-06-21_16h16m24s_buildcommand_ac8bd626-6137-4747-84dd-5d4f215c876c/buck-machine-log
  test/com/facebook/buck/doctor/testdata/report/buck-out/log/2016-06-21_16h16m24s_buildcommand_ac8bd626-6137-4747-84dd-5d4f215c876c/buck-machine-log_duplicate_cmd_args
  test/com/facebook/buck/doctor/testdata/report/buck-out/log/2016-06-21_16h16m24s_buildcommand_ac8bd626-6137-4747-84dd-5d4f215c876c/buck.log
  test/com/facebook/buck/doctor/testdata/report/buck-out/log/2016-06-21_16h16m24s_buildcommand_ac8bd626-6137-4747-84dd-5d4f215c876c/buckconfig.json
  test/com/facebook/buck/doctor/testdata/report/buck-out/log/2016-06-21_16h16m24s_buildcommand_ac8bd626-6137-4747-84dd-5d4f215c876c/rule_key_diag_graph.txt
  test/com/facebook/buck/doctor/testdata/report/buck-out/log/2016-06-21_16h16m24s_buildcommand_ac8bd626-6137-4747-84dd-5d4f215c876c/rule_key_diag_keys.txt
  test/com/facebook/buck/log/testdata/LogFileHandlerTest/buck-out/log/2016-06-21_16h16m24s_buildcommand_ac8bd626-6137-4747-84dd-5d4f215c876c/buck.log
  test/com/facebook/buck/log/testdata/LogFileHandlerTest/buck-out/log/2016-06-21_16h18m51s_autodepscommand_d09893d5-b11e-4e3f-a5bf-70c60a06896e/buck.log
  test/com/facebook/buck/support/fix/testdata/report/buck-out/log/2019-05-21_15h18m52s_launch_0a5e279b-b8de-efa2-202a-d5caf9812d59/buck.log
  test/com/facebook/buck/support/fix/testdata/report/buck-out/log/2019-05-21_15h18m53s_buildcommand_2ef9b523-fc4e-48a3-aa9f-baab9ca36386/buck-machine-log
  test/com/facebook/buck/support/fix/testdata/report/buck-out/log/2019-05-21_15h18m53s_buildcommand_2ef9b523-fc4e-48a3-aa9f-baab9ca36386/buck-machine-log_missing_build_id
  test/com/facebook/buck/support/fix/testdata/report/buck-out/log/2019-05-21_15h18m53s_buildcommand_2ef9b523-fc4e-48a3-aa9f-baab9ca36386/buck-machine-log_missing_command_args
  test/com/facebook/buck/support/fix/testdata/report/buck-out/log/2019-05-21_15h18m53s_buildcommand_2ef9b523-fc4e-48a3-aa9f-baab9ca36386/buck-machine-log_missing_exit_code
  test/com/facebook/buck/support/fix/testdata/report/buck-out/log/2019-05-21_15h18m53s_buildcommand_2ef9b523-fc4e-48a3-aa9f-baab9ca36386/buck-machine-log_missing_unexpanded_command_args
  test/com/facebook/buck/support/fix/testdata/report/buck-out/log/2019-05-21_15h18m53s_buildcommand_2ef9b523-fc4e-48a3-aa9f-baab9ca36386/buck.log
  test/com/facebook/buck/support/fix/testdata/report/buck-out/log/2019-05-21_15h18m53s_buildcommand_2ef9b523-fc4e-48a3-aa9f-baab9ca36386/buckconfig.json
  test/com/facebook/buck/support/fix/testdata/report/buck-out/log/2019-05-21_15h18m53s_buildcommand_2ef9b523-fc4e-48a3-aa9f-baab9ca36386/build.2019-05-21.08-18-53.2ef9b523-fc4e-48a3-aa9f-baab9ca36386.trace
  test/com/facebook/buck/support/fix/testdata/report/buck-out/log/2019-05-21_15h18m53s_buildcommand_2ef9b523-fc4e-48a3-aa9f-baab9ca36386/rule_key_diag_graph.txt
  test/com/facebook/buck/support/fix/testdata/report/buck-out/log/2019-05-21_15h18m53s_buildcommand_2ef9b523-fc4e-48a3-aa9f-baab9ca36386/rule_key_logger.tsv
  test/com/facebook/buck/support/fix/testdata/report/buck-out/log/2019-05-21_15h18m53s_buildcommand_2ef9b523-fc4e-48a3-aa9f-baab9ca36386/upload-build-trace.log
  test/com/facebook/buck/support/fix/testdata/report/buck-out/log/2019-05-21_15h54m33s_launch_f15b0963-e77b-7f2c-281a-992afdc386e8/buck.log
  third-party/py/pytest/src/_pytest/_version.py
Labels: CLA Signed, fh:direct-merge-enabled

#2558 Sync .idea codeStyles settings
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
Labels: CLA Signed, fh:direct-merge-enabled
